spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.100.4:3306/zkrcw?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
  application:
    name: logDemoApplication


logging:
  config: classpath:logback-boot.xml
server:
  port: 9999

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}






