spring:
  datasource:
    url: jdbc:mysql://10.100.100.4:3306/zkrcw?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6666
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    connect-timeout: 5000
  application:
    name: logDemoApplication
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://130.10.7.252/userDetails
  kafka:
    bootstrap-servers: localhost:6668
    producer:
      retries: 3
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer





log-demo:
  zookeeper:
    url: localhost:6667
    timeout: 5000
    retry: 10
  etcd:
    url: localhost:2379
  canal-monitor-mysql:
    host: 130.10.7.157
    port: 11111
    tableName: zkrc_zph_bqjlb


logging:
  config: classpath:logback-boot.xml
server:
  port: 9999

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}






