spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://130.10.7.227:3306/hdjypt-wy2?useSSL=false&useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: 1qaz@WSX




logging:
  config: classpath:logback-boot.xml
server:
  port: 9999

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false